behaviors:
  AirHockey:
    trainer_type: ppo
    max_steps: 3e8         # ~3 million env steps
    time_horizon: 256
    summary_freq: 10000
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 4
    hyperparameters:
      learning_rate: 3.0e-4
      batch_size: 1024
      buffer_size: 10240
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    self_play:
      window: 5
      team_change: 200000
      swap_steps: 50000
